FROM sbtscala/scala-sbt:eclipse-temurin-11.0.16_1.7.2_2.12.17

WORKDIR /hascoapi

RUN git clone --branch hascoapi_docker https://github.com/HADatAc/hascoapi.git .

RUN sbt update

EXPOSE 9000

# Comando para iniciar o serviço usando sbt
CMD ["sbt", "run"]
