FROM sbtscala/scala-sbt:eclipse-temurin-11.0.16_1.7.2_2.12.17

WORKDIR /hascoapi

ARG BRANCH

RUN if [ -z "$BRANCH" ]; then echo "Erro: BRANCH não especificado"; exit 1; fi

RUN git clone --branch $BRANCH https://github.com/HADatAc/hascoapi.git .

RUN apt-get update && \
    apt-get install -y tmux && \
    rm -rf /var/lib/apt/lists/*

RUN sbt update

EXPOSE 9000

CMD ["tmux", "new-session", "-s", "hascoapi", "sbt run"]
