# Usar uma imagem base com JDK 17
FROM openjdk:17-slim

# Definir o diretório de trabalho
WORKDIR /opt/development

# Instalar dependências do sistema
RUN apt-get update && \
    apt-get install -y \
    wget \
    curl \
    unzip \
    xvfb \
    chromium \
    ca-certificates \
    libnss3 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libx11-xcb1 \
    libxcomposite1 \
    libxrandr2 \
    libgbm1 \
    libgtk-3-0 \
    libasound2 && \
    rm -rf /var/lib/apt/lists/*

# Baixar e instalar o Google Chrome
RUN wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_131.0.6778.69-1_amd64.deb && \
    apt install -y ./google-chrome-stable_131.0.6778.69-1_amd64.deb && \
    rm google-chrome-stable_131.0.6778.69-1_amd64.deb

# Baixar e instalar o ChromeDriver
RUN DRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chromedriver-linux64.zip" && \
    curl -L -o chromedriver.zip "$DRIVER_URL" && \
    mkdir -p /usr/local/chromedriver && \
    unzip -o chromedriver.zip -d /usr/local/chromedriver/ && \
    rm chromedriver.zip && \
    mv /usr/local/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver && \
    chmod +x /usr/local/bin/chromedriver

# Baixar e configurar Selenium Standalone
RUN curl -L -o selenium-server.jar https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-server/latest/selenium-server-latest.jar

# Baixar e configurar JUnit 4.13.2 e Hamcrest
RUN mkdir -p /opt/development/junit4 && \
    curl -L -o /opt/development/junit4/junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar && \
    curl -L -o /opt/development/junit4/hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

# Copiar os arquivos de teste para o container
COPY ./tests /opt/development/tests/

# Script para executar os testes com Xvfb
COPY ./hascogui/run-tests.sh /opt/development/run-tests.sh

# Tornar o script executável
RUN chmod +x /opt/development/run-tests.sh

# Expor DISPLAY para usar o Xvfb
ENV DISPLAY=:99

# Definir o comando padrão para iniciar o bash
CMD ["bash"]