version: '3'

services:
  drupal:
    build:
      context: ./hascogui
      dockerfile: Dockerfile-development
      args:
        BRANCH: ${BRANCH}
    container_name: drupal
    ports:
      - "80:80"
    volumes:
      - drupal-data:/opt/drupal/web
    environment:
      DB_HOST: db
      DB_NAME: drupal
      DB_USER: drupal
      DB_PASS: drupal
      DOCKER_COMPOSE_FILE: docker-compose-hascogui-development.yml

    depends_on:
      - db
    networks:
      hascoapi:
        aliases:
          - drupal
    command: ["apache2-foreground"]

  db:
    image: uselagoon/mariadb-10.6-drupal:22.2.0
    container_name: drupal_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db-data:/var/lib/mysql
    networks:
      hascoapi:
        aliases:
          - db

volumes:
  drupal-data:
  db-data:

networks:
  hascoapi:
